#!/usr/bin/env python

import datetime
import csv
import glob
import os.path

input_dir = '/Users/valeria/Documents/Data/Import'
output_dir = '/Users/valeria/Documents/Data/Output'

input_files = glob.glob(input_dir+'/*.csv')

# Function for loading csv data from file
def load_data(input_file, in_delimiter):
  print "[LOAD] Loading data from file '"+input_file+"'"
  csv_data = csv.reader(open(input_file), delimiter=in_delimiter)
  return csv_data

# Function for outputing csv data
def print_csv_data(data):
  print "CSV data:"
  for row in data:
    print(row)

# Function for writing data to csv output file
def write_csv_file(output_file, out_delimiter):
  print "Writing output file '"+output_file+"' ..."
  with open(output_file, 'wb') as csv_out_file:
    spamwriter = csv.writer(csv_out_file, delimiter=out_delimiter)
    spamwriter.writerow(['Spam'] * 5 + ['Baked Beans'])
    spamwriter.writerow(['Spam', 'Lovely Spam', 'Wonderful Spam'])

# Functions checks if element is a number or float
def is_num(str):
  try:
    float(str)
  except:
    return False
  return True

# Function converts point to comma (float conversion us -> deu)
def point2comma(num):
  return str(num).replace('.',',')

# Function creates converted (deu) file
def deu_convert(input_file, in_delimiter):
  data = load_data(input_file, in_delimiter)
  print "[WRITE] Writing data to '"+deu_output_file_name(input_file)+"'"
  writer = csv.writer(open(deu_output_file_name(input_file),'wb'), delimiter = in_delimiter)
  for row in data:
    i = 0
    for cell in row:
      if is_num(cell):
        row[i] = point2comma(cell)
      i += 1
    writer.writerow(row)

# Function returns output file name for point to comma convertion
def deu_output_file_name(input_file):
  return input_file.replace(input_dir, output_dir).replace('.csv','.deu.csv')

# Main function
def main():
  # Importing ShopWare data and converting to comma (deu)a
  for input_file in input_files:
    if os.path.exists(deu_output_file_name(input_file)):
      print "[SKIP] Skipping convertion for output file '"+deu_output_file_name(input_file)+"' (already exists)"
    else:
      print "[CONV] Converting data to output file '"+deu_output_file_name(input_file)+"' (point to comma)"
      shopware_deu_file = deu_convert(input_file, ';')

  # Print ShopWare data
  #print_csv_data(load_data(shopware_deu_file, ';'))

if __name__ == "__main__":
    main()

