#!/bin/bash

if [[ "$#" -ne "2" ]]; then
  echo "Invalid number of argument"
  echo "USAGE: $0 <INPUT_FILE> <OUTPUT_FILE>"
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "Input file '$1' not found!"
  exit 1
fi


if [ -f "$2" ]; then
  echo "Ouput file '$2' exists!"
  exit 1
fi

touch "$2" || echo "Can't create output file '$2'"; exit 1

echo "Converting '$1' ot '$2'..."
cat "$1" | sed -e 's/\./,/g' > "$2"
